name: Compile and Test C Program

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up GCC
        run: sudo apt-get install -y gcc

      - name: Compile C program
        run: gcc -o my_program hello.c

      - name: Run tests
        run: |
          if ./my_program; then
            echo "Test Passed"
          else
            echo "Test Failed"
            exit 1
          fi
        
      - name: Upload executable
        uses: actions/upload-artifact@v4
        with:
            name: my_program
            path: my_program
            retention-days: 1